In [2]:
import numpy as np

A = np.array(np.arange(16)).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
A[1,2]

6

In [4]:
#Indexing Rows, Columns, and Submatricies

In [6]:
A[[1,3]] # row 1 and 3

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [7]:
A[:,[0,2]] # columns 0 and 2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [10]:
A[[1,3],[0,2]]

array([ 4, 14])

In [14]:
print('identical to and a trick because')
np.array([A[1,0],A[3,2]])

identical to and a trick because


array([ 4, 14])

In [15]:
A[[1,3],[0,2,3]]
# What is happening is when supplied with two indexing lists, the numpy interpretation
# is that these provide pairs of i,j indicies for a series of entries.
# That is why the pair of lists must have the same length

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [21]:
idx = np.ix_([1,3],[0,2,3])
A[idx]

# np.ix() allows us to extract a submatrix using lists creating an intermidiate mesh object

array([[ 4,  6,  7],
       [12, 14, 15]])

In [23]:
#using slices
A[1:4:2,0:3:2]

#1:4:2 captures teh second and fourth items of a sequence, 
# 0:3:2 captures the first and third items

array([[ 4,  6],
       [12, 14]])

In [24]:
#Boolean Indexing

In [27]:
keep_rows = np.zeros(A.shape[0], bool)
keep_rows

# creates a vector of 0's represented of Booleans of length equal to the first dimension of A

array([False, False, False, False])

In [28]:
keep_rows[[1,3]] = True
keep_rows

array([False,  True, False,  True])

In [31]:
np.all(keep_rows == np.array([0,1,0,1]))
# np.all checked whether all the entries are true

True

In [33]:
A[np.array([0,1,0,1])]

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
A[keep_rows]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [36]:
keep_cols = np.zeros(A.shape[1], bool)
keep_cols[[0,2,3]] = True
idx_bool = np.ix_(keep_rows, keep_cols)
A[idx_bool]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [37]:
# we can also mix a list with an array of Booleans
idx_mixed = np.ix_([1,3], keep_cols)
A[idx_mixed]

array([[ 4,  6,  7],
       [12, 14, 15]])